//! Live-HTTP verification of the cross-repo download fallback added to
//! `download_all_ex`: when a package's own repo 404s, it should retry the
//! same name+arch from another repo in `alt_candidates` rather than failing
//! outright — mirrors the real `gcc-c++` mirror gap that motivated this.

use rum_core::{Comparator, Dependency, Nevra, Package};
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::PathBuf;

/// Minimal single-shot HTTP server: replies with `status_line` + `body` to
/// every request it accepts, for `count` requests, then stops. Good enough
/// to stand in for a repo mirror without pulling in an HTTP server crate.
fn spawn_server(count: usize, status_line: &'static str, body: &'static [u8]) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let addr = listener.local_addr().unwrap();
    std::thread::spawn(move || {
        for _ in 0..count {
            let (mut stream, _) = listener.accept().unwrap();
            let mut buf = [0u8; 1024];
            let _ = stream.read(&mut buf);
            let response = format!("{status_line}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n", body.len());
            stream.write_all(response.as_bytes()).unwrap();
            stream.write_all(body).unwrap();
        }
    });
    format!("http://{addr}")
}

fn pkg(name: &str, epoch: u32, version: &str, release: &str, repo_id: &str, location: String) -> Package {
    Package {
        nevra: Nevra { name: name.to_string(), epoch, version: version.to_string(), release: release.to_string(), arch: "x86_64".to_string() },
        summary: String::new(),
        provides: vec![],
        requires: vec![],
        conflicts: vec![],
        obsoletes: vec![],
        recommends: vec![],
        suggests: vec![],
        enhances: vec![],
        supplements: vec![],
        location,
        repo_id: repo_id.to_string(),
        repo_priority: 99,
        repo_cost: 1000,
        install_size: 0,
        download_size: 0,
            vendor: String::new(),
            checksum_type: String::new(),
            checksum: String::new(),
    }
}

#[tokio::test]
async fn falls_back_to_another_repo_on_404() {
    // Primary repo 404s every request (the real `fedoraproject-updates-archive`
    // gap this feature exists for); a second repo actually has the package.
    let dead_base = spawn_server(1, "HTTP/1.1 404 Not Found", b"not found");
    // A successful download costs the mock server 2 requests, not 1:
    // `ripget` always probes with `GET`+`Range: bytes=0-0` first to learn
    // the size/range-support (`fetch_metadata`), then issues a second,
    // separate request for the body once it sees this server doesn't
    // support ranges. `dead_base` above only ever needs 1, since its 404 is
    // a fatal status `fetch_metadata` returns on immediately, before ever
    // reaching a second request.
    let alive_base = spawn_server(2, "HTTP/1.1 200 OK", b"fake rpm bytes");

    let requested = pkg("gcc-c++", 1, "16.1.1", "2.fc44", "updates-archive", format!("{dead_base}/gcc-c++-16.1.1-2.fc44.x86_64.rpm"));
    let alt = pkg("gcc-c++", 1, "16.1.1", "1.fc44", "fedora", format!("{alive_base}/gcc-c++-16.1.1-1.fc44.x86_64.rpm"));

    let tmp = tempdir();
    let client = reqwest::Client::new();
    let result = rum_transaction::download_all_ex(&client, &[requested.clone()], &tmp, 1, false, &[], &[alt.clone()]).await.expect("fallback download should succeed");

    assert_eq!(result.len(), 1);
    // The fallback build's own EVR/repo should be what actually landed, not
    // the originally-requested (404ing) one.
    assert_eq!(result[0].package.nevra.to_string(), alt.nevra.to_string());
    assert_eq!(result[0].package.repo_id, "fedora");
    assert!(result[0].rpm_path.exists());
    assert_eq!(std::fs::read(&result[0].rpm_path).unwrap(), b"fake rpm bytes");
}

/// Reproduces the real failure this fallback caused in production: `gcc-c++`
/// 404s, and another repo happens to have a *different* build (`16.0.1`
/// instead of `16.1.1`) — but that build's autogenerated `Requires: gcc =
/// 16.0.1` doesn't match the `gcc-16.1.1-2` actually landing in this same
/// transaction. Blindly accepting it downloads fine but then fails at `rpm`
/// transaction time; the fallback must reject it up front instead.
#[tokio::test]
async fn rejects_fallback_whose_requires_break_the_transaction() {
    let dead_base = spawn_server(1, "HTTP/1.1 404 Not Found", b"not found");
    // Second repo would happily serve the mismatched build if asked — the
    // test fails if the fallback logic ever reaches for it.
    let mismatched_base = spawn_server(0, "HTTP/1.1 200 OK", b"unused");

    let gcc = pkg("gcc", 0, "16.1.1", "2.fc44", "updates-archive", "unused://gcc".to_string());
    let requested = pkg("gcc-c++", 0, "16.1.1", "2.fc44", "updates-archive", format!("{dead_base}/gcc-c++-16.1.1-2.fc44.x86_64.rpm"));
    let mut alt = pkg("gcc-c++", 0, "16.0.1", "0.10.fc44", "fedora", format!("{mismatched_base}/gcc-c++-16.0.1-0.10.fc44.x86_64.rpm"));
    alt.requires = vec![Dependency { name: "gcc".to_string(), constraint: Some((Comparator::Eq, "16.0.1-0.10.fc44".to_string())) }];

    let tmp = tempdir();
    let client = reqwest::Client::new();
    let result = rum_transaction::download_all_ex(&client, &[gcc, requested], &tmp, 1, false, &[], &[alt]).await;
    assert!(result.is_err(), "must not silently accept a fallback build that breaks the transaction's own dependency graph");
}

#[tokio::test]
async fn fails_cleanly_when_no_fallback_available() {
    let dead_base = spawn_server(1, "HTTP/1.1 404 Not Found", b"not found");
    let requested = pkg("gcc-c++", 1, "16.1.1", "2.fc44", "updates-archive", format!("{dead_base}/gcc-c++-16.1.1-2.fc44.x86_64.rpm"));

    let tmp = tempdir();
    let client = reqwest::Client::new();
    let result = rum_transaction::download_all_ex(&client, &[requested], &tmp, 1, false, &[], &[]).await;
    assert!(result.is_err(), "should fail cleanly when no other repo has the package");
}

fn tempdir() -> PathBuf {
    let dir = std::env::temp_dir().join(format!("rum-download-fallback-test-{}", std::process::id())).join(uniqueish());
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn uniqueish() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    format!("{}-{}", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos(), COUNTER.fetch_add(1, Ordering::Relaxed))
}
