[main]
gpgcheck=1
best=1
skip_if_unavailable=0
install_weak_deps=0
clean_requirements_on_remove=0
protected_packages=rakuos-core,rakuos-rum,rum-dnf-shim,bootc,ostree,plasma-workspace,kwin,plasma-login-manager
protect_running_kernel=1
